-- ============================================================================
-- Product Maintenance Tasks Cache
--
-- Stores AI-generated (and eventually manufacturer-verified) maintenance tasks
-- keyed to product_registry entries. Shared across all boats and users —
-- once generated for a Volvo Penta D2-75, all subsequent boats with the same
-- engine get the tasks from this cache at zero AI cost.
--
-- source: 'ai'           — generated by the AI job worker
--         'manufacturer' — imported from official service documentation
--         'manual'       — added or edited by an admin/user
-- ============================================================================

create table if not exists public.product_maintenance_tasks (
  id                    uuid primary key default gen_random_uuid(),
  product_registry_id   uuid not null references public.product_registry(id) on delete cascade,
  title                 text not null,
  description           text,
  category              text not null check (category in ('routine', 'seasonal', 'repair', 'inspection', 'safety')),
  priority              text not null default 'medium' check (priority in ('low', 'medium', 'high', 'critical')),
  recurrence            jsonb,           -- {type: 'time', interval_days: N} or {type: 'usage', engine_hours: N}
  estimated_hours       numeric,
  instructions          text,
  source                text not null default 'ai' check (source in ('ai', 'manufacturer', 'manual')),
  is_verified           boolean not null default false,  -- true = reviewed against manufacturer documentation
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_product_maint_tasks_registry_id
  on public.product_maintenance_tasks(product_registry_id);

alter table public.product_maintenance_tasks enable row level security;

-- Anyone can read the shared maintenance task library
create policy "Anyone can view product maintenance tasks"
  on public.product_maintenance_tasks for select using (true);

-- Only service role (edge functions) writes to this table; no direct user writes
-- No insert/update/delete policies for authenticated users — edge functions use service role
