-- ============================================================================
-- Product Spare Parts Cache (Migration 058)
-- Stores AI-generated (and eventually manufacturer-verified) spare parts
-- keyed to product_registry entries. Shared across all boats and users —
-- once generated for a Yanmar 3YM30, all subsequent boats with the same
-- engine get the parts list from this cache at zero AI cost.
--
-- source: 'ai'           — generated by the AI job worker
--         'manufacturer' — imported from official spare parts documentation
--         'manual'       — added or edited by an admin/user
-- ============================================================================

create table if not exists public.product_spare_parts (
  id                    uuid primary key default gen_random_uuid(),
  product_registry_id   uuid not null references public.product_registry(id) on delete cascade,
  name                  text not null,
  part_number           text,
  category              text not null,
  description           text,
  quantity              integer not null default 1,
  unit                  text not null default 'pieces',
  notes                 text,
  source                text not null default 'ai' check (source in ('ai', 'manufacturer', 'manual')),
  is_verified           boolean not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_product_spare_parts_registry_id
  on public.product_spare_parts(product_registry_id);

alter table public.product_spare_parts enable row level security;

-- Anyone can read the shared spare parts library
create policy "Anyone can view product spare parts"
  on public.product_spare_parts for select using (true);

-- Only service role (edge functions) writes to this table; no direct user writes
