-- Add AI generation fields to journeys table
-- This tracks whether a journey was generated by AI and stores the prompt used

ALTER TABLE public.journeys 
ADD COLUMN IF NOT EXISTS is_ai_generated boolean DEFAULT false;

ALTER TABLE public.journeys 
ADD COLUMN IF NOT EXISTS ai_prompt text;

-- Add a comment to document the fields
COMMENT ON COLUMN public.journeys.is_ai_generated IS 'Indicates if the journey was generated by AI';
COMMENT ON COLUMN public.journeys.ai_prompt IS 'Stores the prompt used for AI journey generation';
